DROP TABLE IF EXISTS RESIDENT_CREDENTIAL ;

CREATE TABLE RESIDENT_CREDENTIAL (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100),
    RESIDENT_ID INT,
    FOREIGN KEY (RESIDENT_ID) REFERENCES RESIDENT(ID)
);

--Insert multiple sample data
INSERT INTO RESIDENT_CREDENTIAL (USERNAME, PASSWORD, CREATED_DATE, CREATED_BY)
VALUES ("root", "root", NOW(), "SYSTEM");