DROP TABLE IF EXISTS NOTICE;

CREATE TABLE NOTICE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(100) NOT NULL UNIQUE,
    CONTENT BLOB NOT NULL,
    IS_ACTIVE VARCHAR(1) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRY_DATE VARCHAR(100) NOT NULL,
    CREATED_BY VARCHAR(100) NOT NULL
);

INSERT INTO NOTICE (TITLE, MESSAGE, IS_ACTIVE, CREATED_DATE, EXPIRY_DATE, CREATED_BY)
VALUES ("title", "message", "Y", NOW(), (SELECT DATE_SUB(CURDATE(), INTERVAL 1 DAY) AS yesterday), "SYSTEM");

INSERT INTO NOTICE (TITLE, MESSAGE, IS_ACTIVE, CREATED_DATE, EXPIRY_DATE, CREATED_BY)
VALUES ("title2", "message", "Y", NOW(), (SELECT DATE_ADD(CURDATE(), INTERVAL 1 DAY) AS yesterday), "SYSTEM");