CREATE TABLE PAYMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    METHOD VARCHAR(100),
    REFERENCE VARCHAR(100),
    STATUS VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);