DROP TABLE IF EXISTS PAYMENT;

CREATE TABLE PAYMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    METHOD VARCHAR(100),
    REFERENCE VARCHAR(100),
    STATUS VARCHAR(100),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATEMENT_ID INT,
    FOREIGN KEY (STATEMENT_ID) REFERENCES STATEMENT(ID)
);