CREATE TABLE RECEIPT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(100) NOT NULL,
    PAYMENT_ID INT,
    FOREIGN KEY (PAYMENT_ID) REFERENCES PAYMENT(ID)
);