DROP TABLE IF EXISTS STATEMENT;

CREATE TABLE STATEMENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    YEAR INT NOT NULL,
    MONTH INT NOT NULL,
    STATUS INT NOT NULL,
    CLIENT_ID INT,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);