DROP TABLE IF EXISTS VISITOR_PASS;

CREATE TABLE VISITOR_PASS (
    UUID VARCHAR(50) PRIMARY KEY,
    VISITOR_NAME VARCHAR(50) NOT NULL,
    RESIDENT_UNIT VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    RESIDENT_ID INT,
    FOREIGN KEY (RESIDENT_ID) REFERENCES RESIDENT(ID)
);

