DROP TABLE IF EXISTS VISITOR_PASS;

CREATE TABLE VISITOR_PASS (
    UUID VARCHAR(50) PRIMARY KEY,
    VISITOR_NAME VARCHAR(50) NOT NULL,
    CLIENT_UNIT VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CLIENT_ID INT,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);

