DROP TABLE IF EXISTS RESIDENT;

CREATE TABLE RESIDENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    AGE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE_NO VARCHAR(100) NOT NULL,
    UNIT_NO VARCHAR(100) NOT NULL,
    STATUS VARCHAR(100) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO RESIDENT
VALUES (1, "test name", "123", "liyu@gmail.com", "0134567890", "C7-20", "Active", NOW());

INSERT INTO RESIDENT
VALUES (2, "test name 2", "123", "liyu@gmail.com", "0134567890", "C7-20", "Active", NOW());