DROP TABLE IF EXISTS EMERGENCY_REQUEST;

CREATE TABLE EMERGENCY_REQUEST (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    MESSAGE VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CLIENT_ID INT,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(ID)
);