DROP TABLE IF EXISTS EMERGENCY_REQUEST;

CREATE TABLE EMERGENCY_REQUEST (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    MESSAGE VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    RESIDENT_ID INT,
    FOREIGN KEY (RESIDENT_ID) REFERENCES RESIDENT(ID)
);

INSERT INTO EMERGENCY_REQUEST
VALUES (1, "title test", "anything", "ACTIVE", 25);

INSERT INTO EMERGENCY_REQUEST
VALUES (2, "this is title", "ng chan han", "ACTIVE", 25);
