server:
  port: 8083

spring:
  application:
    name: residential-admin-backend

# gen secret key using CustomLoginSuccessHandler#generateKey()
jwt:
  secret:
    key: G5Sg5suNMasyHNHgknc9ShSIyE9PH9h8Osz6E1qZMGl/oeSRlCZ38k3SAeG9hbWGiOo/QMyIuxgD7JmGkHiclQ==